apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftpython
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftpython
  template:
    metadata:
      labels:
        app: ftpython
    spec:
      containers:
      - name: ftpython
        image: techmago/docker-ftpython:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "50M"
          limits:
            memory: "250M"
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 0
          timeoutSeconds: 5
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      dnsConfig:
        options:
          - name: ndots
            value: "1"

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: ftpython
# spec:
#   type: ClusterIP
#   ports:
#   - port: 80
#     targetPort: 8000
#   selector:
#     app: ftpython
#
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ftpython
# spec:
#   rules:
#   - host: ftpython.com.br
#     http:
#       paths:
#       - backend:
#           service:
#             name: ftpython
#             port:
#               number: 80
#         path: "/"
#        pathType: Prefix
